# Generated by Django 2.0.4 on 2018-05-03 16:11

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='company_adress',
            field=models.CharField(blank=True, db_index=True, max_length=200),
        ),
        migrations.AddField(
            model_name='ad',
            name='company_name',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='ad',
            name='company_type',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='ad',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='ad',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='ad',
            name='photo',
            field=models.ImageField(blank=True, upload_to='ads', verbose_name='Фото продукции'),
        ),
        migrations.AddField(
            model_name='ad',
            name='position',
            field=models.CharField(blank=True, db_index=True, max_length=200),
        ),
        migrations.AddField(
            model_name='ad',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ad',
            name='volume',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
