# Generated by Django 2.0.3 on 2018-05-07 20:14

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180503_1611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='company_type',
        ),
        migrations.AlterField(
            model_name='ad',
            name='category',
            field=models.IntegerField(choices=[(1, 'Купить вторичное сырье на переработку'), (2, 'Купить переработанное сырье'), (3, 'Продать вторичное сырье на переработку'), (4, 'Продать переработанное сырье')], default=0),
        ),
        migrations.AlterField(
            model_name='ad',
            name='company_adress',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='ad',
            name='company_name',
            field=models.CharField(db_index=True, default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ad',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ad',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='ad',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128),
        ),
        migrations.AlterField(
            model_name='ad',
            name='photo',
            field=models.ImageField(blank=True, upload_to='images/ad', verbose_name='Фото продукции'),
        ),
    ]
