# Generated by Django 2.0.3 on 2018-05-07 20:52

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180507_2014'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ad',
            old_name='price',
            new_name='price_max',
        ),
        migrations.AddField(
            model_name='ad',
            name='phone_another',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='ad',
            name='price_min',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
