# Generated by Django 2.0.3 on 2018-05-07 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20180507_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='photo',
            field=models.ImageField(blank=True, upload_to='prod_img', verbose_name='Фото продукции'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='volume',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
    ]
