# Generated by Django 2.0.3 on 2018-05-07 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20180507_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='volume',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
