# Generated by Django 2.0.3 on 2018-05-08 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_merchant'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=254, null=True, unique=True),
        ),
    ]
