# Generated by Django 2.0.4 on 2018-06-02 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20180602_1056'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ad',
            old_name='price_max',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='price_min',
        ),
    ]
