# Generated by Django 2.0.5 on 2018-06-16 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20180602_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='category1',
            field=models.IntegerField(blank=True, choices=[(1, 'ПП'), (2, 'ПНД'), (3, 'ПВД'), (4, 'Стрейч'), (5, 'ПЭТ'), (6, 'Другое')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ad',
            name='category2',
            field=models.IntegerField(blank=True, choices=[(1, 'Гранула ПП'), (2, 'Гранула ПНД'), (3, 'Гранула ПВД'), (4, 'Гранула стрейч'), (5, 'Другое')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ad',
            name='position',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
    ]
