# Generated by Django 2.0.4 on 2018-06-23 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20180616_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='company_name',
            field=models.CharField(db_index=True, max_length=200, null=True),
        ),
    ]
